require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'

PuppetLint.configuration.fail_on_warnings = true
PuppetLint.configuration.send('disable_80chars')
PuppetLint.configuration.ignore_paths = ['spec/**/*.rb']

desc 'Validate Puppet code and templates'
task :validate do
  sh 'bundle exec puppet parser validate manifests/*.pp'
  sh 'bundle exec puppet epp validate templates/*.epp'
end

task default: [:validate, :spec]
