source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'puppet', '~> 8.0'
gem 'puppet-lint', '~> 4.0'
gem 'metadata-json-lint', '~> 3.0'
gem 'puppetlabs_spec_helper', '~> 8.0'
gem 'rspec-puppet', '~> 5.0'
